package com.huofu.RestaurantOS.support.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MENU_DETAIL.
 */
public class MenuDetail {

    private String menuDateId;
    private Long menuId;
    private Integer widgetId;
    private String type;
    private String name;
    private Double x;
    private Double y;
    private Integer price;
    private Integer fontSize;
    private String fontColor;
    private String backgroundColor;
    private Double distance;
    private String addtiontal;
    private Integer BindToItemServerId;
    private String redundance1;
    private String redundance2;
    private String redundance3;
    private String redundance4;
    private String redundance5;

    public MenuDetail() {
    }

    public MenuDetail(String menuDateId, Long menuId, Integer widgetId, String type, String name, Double x, Double y, Integer price, Integer fontSize, String fontColor, String backgroundColor, Double distance, String addtiontal, Integer BindToItemServerId, String redundance1, String redundance2, String redundance3, String redundance4, String redundance5) {
        this.menuDateId = menuDateId;
        this.menuId = menuId;
        this.widgetId = widgetId;
        this.type = type;
        this.name = name;
        this.x = x;
        this.y = y;
        this.price = price;
        this.fontSize = fontSize;
        this.fontColor = fontColor;
        this.backgroundColor = backgroundColor;
        this.distance = distance;
        this.addtiontal = addtiontal;
        this.BindToItemServerId = BindToItemServerId;
        this.redundance1 = redundance1;
        this.redundance2 = redundance2;
        this.redundance3 = redundance3;
        this.redundance4 = redundance4;
        this.redundance5 = redundance5;
    }

    public String getMenuDateId() {
        return menuDateId;
    }

    public void setMenuDateId(String menuDateId) {
        this.menuDateId = menuDateId;
    }

    public Long getMenuId() {
        return menuId;
    }

    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    public Integer getWidgetId() {
        return widgetId;
    }

    public void setWidgetId(Integer widgetId) {
        this.widgetId = widgetId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getX() {
        return x;
    }

    public void setX(Double x) {
        this.x = x;
    }

    public Double getY() {
        return y;
    }

    public void setY(Double y) {
        this.y = y;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Integer getFontSize() {
        return fontSize;
    }

    public void setFontSize(Integer fontSize) {
        this.fontSize = fontSize;
    }

    public String getFontColor() {
        return fontColor;
    }

    public void setFontColor(String fontColor) {
        this.fontColor = fontColor;
    }

    public String getBackgroundColor() {
        return backgroundColor;
    }

    public void setBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
    }

    public Double getDistance() {
        return distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

    public String getAddtiontal() {
        return addtiontal;
    }

    public void setAddtiontal(String addtiontal) {
        this.addtiontal = addtiontal;
    }

    public Integer getBindToItemServerId() {
        return BindToItemServerId;
    }

    public void setBindToItemServerId(Integer BindToItemServerId) {
        this.BindToItemServerId = BindToItemServerId;
    }

    public String getRedundance1() {
        return redundance1;
    }

    public void setRedundance1(String redundance1) {
        this.redundance1 = redundance1;
    }

    public String getRedundance2() {
        return redundance2;
    }

    public void setRedundance2(String redundance2) {
        this.redundance2 = redundance2;
    }

    public String getRedundance3() {
        return redundance3;
    }

    public void setRedundance3(String redundance3) {
        this.redundance3 = redundance3;
    }

    public String getRedundance4() {
        return redundance4;
    }

    public void setRedundance4(String redundance4) {
        this.redundance4 = redundance4;
    }

    public String getRedundance5() {
        return redundance5;
    }

    public void setRedundance5(String redundance5) {
        this.redundance5 = redundance5;
    }

}
