package com.huofu.RestaurantOS.support.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MENU_TABLE.
 */
public class MenuTable {

    private String menuName;
    private Integer menuType;
    private Long menuId;
    private String menuCreateTime;
    private Long storeId;

    public MenuTable() {
    }

    public MenuTable(Long menuId) {
        this.menuId = menuId;
    }

    public MenuTable(String menuName, Integer menuType, Long menuId, String menuCreateTime, Long storeId) {
        this.menuName = menuName;
        this.menuType = menuType;
        this.menuId = menuId;
        this.menuCreateTime = menuCreateTime;
        this.storeId = storeId;
    }

    public String getMenuName() {
        return menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public Integer getMenuType() {
        return menuType;
    }

    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    public Long getMenuId() {
        return menuId;
    }

    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    public String getMenuCreateTime() {
        return menuCreateTime;
    }

    public void setMenuCreateTime(String menuCreateTime) {
        this.menuCreateTime = menuCreateTime;
    }

    public Long getStoreId() {
        return storeId;
    }

    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

}
